
DELETE FROM "TESTDB.DB".TESTDB.CATEGORY;
DELETE FROM "TESTDB.DB".TESTDB.PRODUCT;
DELETE FROM "TESTDB.DB".TESTDB.CATEGORY_PRODUCT;

INSERT INTO "TESTDB.DB".TESTDB.CATEGORY (ID,CODE,NAME) VALUES (1,'vegetables','Vegetables');
INSERT INTO "TESTDB.DB".TESTDB.CATEGORY (ID,CODE,NAME) VALUES (2,'fruits','Fruits');

INSERT INTO "TESTDB.DB".TESTDB.PRODUCT (ID,AID,CATEGORY_ID,TITLE,AMOUNT,PRICE) VALUES (1,1,1,'Potatoes',5,100);
INSERT INTO "TESTDB.DB".TESTDB.PRODUCT (ID,AID,CATEGORY_ID,TITLE,AMOUNT,PRICE) VALUES (2,2,1,'Cabbage',7,80);
INSERT INTO "TESTDB.DB".TESTDB.PRODUCT (ID,AID,CATEGORY_ID,TITLE,AMOUNT,PRICE) VALUES (3,3,1,'Carrot',22,65);
INSERT INTO "TESTDB.DB".TESTDB.PRODUCT (ID,AID,CATEGORY_ID,TITLE,AMOUNT,PRICE) VALUES (4,4,2,'Bananas',9,200);
INSERT INTO "TESTDB.DB".TESTDB.PRODUCT (ID,AID,CATEGORY_ID,TITLE,AMOUNT,PRICE) VALUES (5,5,2,'Oranges',11,130);
INSERT INTO "TESTDB.DB".TESTDB.PRODUCT (ID,AID,CATEGORY_ID,TITLE,AMOUNT,PRICE) VALUES (6,6,2,'Pineapples',48,265);